## Introduction

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [2]:
df = pd.read_csv("AmesHousing.tsv", delimiter='\t')
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

### Helper functions

In [3]:
def transform_features(df):
    return df

def select_features(df):
    return df[['Gr Liv Area', 'SalePrice']]

def train_and_test(df):
    train = df[:1460]
    test = df[1460:]
    
    numeric_train = train.select_dtypes(include=['integer', 'float'])
    numeric_test = test.select_dtypes(include=['integer', 'float'])
    # numeric features
    features = numeric_train.columns.drop('SalePrice')
    target = 'SalePrice'
    
    lr = LinearRegression()
    lr.fit(train[features], train[target])
    predictions = lr.predict(test[features])
    mse = mean_squared_error(test[target], predictions)
    rmse = np.sqrt(mse)
    
    return rmse

transform_df = transform_features(df)
filtered_df = select_features(transform_df)
rmse = train_and_test(filtered_df)

rmse

57088.251612639091

## Feature Engineering

- Handle missing values:
    - All columns:
        - Drop any with 5% or more missing values **for now**
    - Text columns:
        - Drop any with 1 or more missing values ** for now**
    - Numericla columns:
        - For columns with missing vlaues, fill in with the most common values in that colum

In [4]:
# Number of missing values in each column
num_missing = df.isnull().sum()
num_missing

Order                0
PID                  0
MS SubClass          0
MS Zoning            0
Lot Frontage       490
Lot Area             0
Street               0
Alley             2732
Lot Shape            0
Land Contour         0
Utilities            0
Lot Config           0
Land Slope           0
Neighborhood         0
Condition 1          0
Condition 2          0
Bldg Type            0
House Style          0
Overall Qual         0
Overall Cond         0
Year Built           0
Year Remod/Add       0
Roof Style           0
Roof Matl            0
Exterior 1st         0
Exterior 2nd         0
Mas Vnr Type        23
Mas Vnr Area        23
Exter Qual           0
Exter Cond           0
                  ...
Bedroom AbvGr        0
Kitchen AbvGr        0
Kitchen Qual         0
TotRms AbvGrd        0
Functional           0
Fireplaces           0
Fireplace Qu      1422
Garage Type        157
Garage Yr Blt      159
Garage Finish      159
Garage Cars          1
Garage Area          1
Garage Qual        159
Garage Cond        159
Paved Drive          0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Pool QC           2917
Fence             2358
Misc Feature      2824
Misc Val             0
Mo Sold              0
Yr Sold              0
Sale Type            0
Sale Condition       0
SalePrice            0
dtype: int64

1: All columns: Drop any with 5% or more missing values for now

In [5]:
# Filter Series to columns containing > 5% missing values
drop_missing_cols = num_missing[num_missing > len(df)/20].index
# print(drop_missing_cols)
df = df.drop(drop_missing_cols, axis=1)
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,31770,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,14267,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,11160,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,13830,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,3,2010,WD,Normal,189900

2: Text columns: Drop any with 1 or more missing values for now

In [6]:
## count missing values in each text column
text_mv_counts = df.select_dtypes(include=['object']).isnull().sum().sort_values(ascending=False)
# print(text_mv_counts)

## Filter Series to columns containing *any* missing values
drop_missing_cols_2 = text_mv_counts[text_mv_counts != 0].index
# print(drop_missing_cols_2)

## drop columns
df = df.drop(drop_missing_cols_2, axis=1)
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,31770,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,14267,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,11160,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,13830,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,3,2010,WD,Normal,189900

3: Numerical columns: For columns with missing vlaues, fill in with the most common values in that colum

In [7]:
## Count missing values in each numeric columns
num_missing = df.select_dtypes(include=['int', 'float']).isnull().sum()
# print(num_missing)

fixable_numeric_cols = num_missing[(num_missing < len(df)/20) & (num_missing > 0)].sort_values()
print(fixable_numeric_cols)

BsmtFin SF 1       1
BsmtFin SF 2       1
Bsmt Unf SF        1
Total Bsmt SF      1
Garage Cars        1
Garage Area        1
Bsmt Full Bath     2
Bsmt Half Bath     2
Mas Vnr Area      23
dtype: int64

In [8]:
## Compute the most common value for each column in 'fixable_numeric_cols'.
replacement_values_dict = df[fixable_numeric_cols.index].mode().to_dict(orient='records')[0]
replacement_values_dict

{'Bsmt Full Bath': 0.0,
 'Bsmt Half Bath': 0.0,
 'Bsmt Unf SF': 0.0,
 'BsmtFin SF 1': 0.0,
 'BsmtFin SF 2': 0.0,
 'Garage Area': 0.0,
 'Garage Cars': 2.0,
 'Mas Vnr Area': 0.0,
 'Total Bsmt SF': 0.0}

In [9]:
## Filling in missing slots
df = df.fillna(replacement_values_dict)

## Verify that every column has 0 missing values
df.isnull().sum().value_counts()

0    64
dtype: int64

- What new features can we create, that better capture the information in some of the features?

In [10]:
years_sold = df['Yr Sold'] - df['Year Built']
years_sold[years_sold < 0]

2180   -1
dtype: int64

In [11]:
years_since_remod = df['Yr Sold'] - df['Year Remod/Add']
years_since_remod[years_since_remod < 0]

1702   -1
2180   -2
2181   -1
dtype: int64

In [12]:
## Create new columns
df['Years Before Sale'] = years_sold
df['Years Since Remod'] = years_since_remod

## Drop rows with negative values for both of these new features
try:
    df = df.drop([1702, 2180, 2181], axis=0)

## No longer need original year columns (no meaningful)
    df = df.drop(['Year Built', 'Year Remod/Add'], axis=1)
except Exception:
    pass

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2927 entries, 0 to 2929
Data columns (total 64 columns):
Order                2927 non-null int64
PID                  2927 non-null int64
MS SubClass          2927 non-null int64
MS Zoning            2927 non-null object
Lot Area             2927 non-null int64
Street               2927 non-null object
Lot Shape            2927 non-null object
Land Contour         2927 non-null object
Utilities            2927 non-null object
Lot Config           2927 non-null object
Land Slope           2927 non-null object
Neighborhood         2927 non-null object
Condition 1          2927 non-null object
Condition 2          2927 non-null object
Bldg Type            2927 non-null object
House Style          2927 non-null object
Overall Qual         2927 non-null int64
Overall Cond         2927 non-null int64
Roof Style           2927 non-null object
Roof Matl            2927 non-null object
Exterior 1st         2927 non-null object
Exterior 2nd         2927 non-null object
Mas Vnr Area         2927 non-null float64
Exter Qual           2927 non-null object
Exter Cond           2927 non-null object
Foundation           2927 non-null object
BsmtFin SF 1         2927 non-null float64
BsmtFin SF 2         2927 non-null float64
Bsmt Unf SF          2927 non-null float64
Total Bsmt SF        2927 non-null float64
Heating              2927 non-null object
Heating QC           2927 non-null object
Central Air          2927 non-null object
1st Flr SF           2927 non-null int64
2nd Flr SF           2927 non-null int64
Low Qual Fin SF      2927 non-null int64
Gr Liv Area          2927 non-null int64
Bsmt Full Bath       2927 non-null float64
Bsmt Half Bath       2927 non-null float64
Full Bath            2927 non-null int64
Half Bath            2927 non-null int64
Bedroom AbvGr        2927 non-null int64
Kitchen AbvGr        2927 non-null int64
Kitchen Qual         2927 non-null object
TotRms AbvGrd        2927 non-null int64
Functional           2927 non-null object
Fireplaces           2927 non-null int64
Garage Cars          2927 non-null float64
Garage Area          2927 non-null float64
Paved Drive          2927 non-null object
Wood Deck SF         2927 non-null int64
Open Porch SF        2927 non-null int64
Enclosed Porch       2927 non-null int64
3Ssn Porch           2927 non-null int64
Screen Porch         2927 non-null int64
Pool Area            2927 non-null int64
Misc Val             2927 non-null int64
Mo Sold              2927 non-null int64
Yr Sold              2927 non-null int64
Sale Type            2927 non-null object
Sale Condition       2927 non-null object
SalePrice            2927 non-null int64
Years Before Sale    2927 non-null int64
Years Since Remod    2927 non-null int64
dtypes: float64(9), int64(28), object(27)
memory usage: 1.5+ MB

### Drop columns:

   - that are not useful for ML
   - leak data about the final sale, reference [here.](https://ww2.amstat.org/publications/jse/v19n3/decock/DataDocumentation.txt)

In [13]:
## Drop columns that aren't useful for ML## Drop c 
df = df.drop(["PID", "Order"], axis=1)

## Drop columns that leak info about the final sale
df = df.drop(["Mo Sold", "Sale Condition", "Sale Type", "Yr Sold"], axis=1)

## Update transform_features( )

In [15]:
def transform_features(df):
## 1: All columns: Drop any with 5% or more missing values
    num_missing = df.isnull().sum()
    drop_missing_cols = num_missing[num_missing > len(df)/20].index
    df = df.drop(drop_missing_cols, axis=1)

## 2: Text columns: Drop any with 1 or more missing values
    text_mv_counts = df.select_dtypes(include=['object']).isnull().sum().sort_values(ascending=False)
    drop_missing_cols_2 = text_mv_counts[text_mv_counts != 0].index
    df = df.drop(drop_missing_cols_2, axis=1)

## 3: Numerical columns: fill in with the most common values in that colum
    num_missing = df.select_dtypes(include=['int', 'float']).isnull().sum()
    fixable_numeric_cols = num_missing[(num_missing < len(df)/20) & (num_missing > 0)].sort_values()
    replacement_values_dict = df[fixable_numeric_cols.index].mode().to_dict(orient='records')[0]
    df = df.fillna(replacement_values_dict)
    
## Adding meaningful features and drop the opposites
    years_sold = df['Yr Sold'] - df['Year Built']
    years_since_remod = df['Yr Sold'] - df['Year Remod/Add']
    df['Years Before Sale'] = years_sold
    df['Years Since Remod'] = years_since_remod
    try:
        df = df.drop([1702, 2180, 2181], axis=0)
        df = df.drop(["Year Built", "Year Remod/Add", \
                      "PID", "Order", "Mo Sold", \
                      "Sale Condition", "Sale Type", \
                      "Yr Sold"], axis=1)
    except Exception:
        pass
    
    return df

df = pd.read_csv("AmesHousing.tsv", delimiter='\t')
transform_df = transform_features(df)
filtered_df = select_features(transform_df)
rmse = train_and_test(filtered_df)

rmse

55275.367312413073

## Feature Selection

- study correlation through heatmap matrix of numericla features in the training data set
    - which features corrleate strongly with the target column, 'SalePrice'?
    - coliniality